package org.dto;

import org.hibernate.annotations.CollectionId;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;
//Know about GenericGenerator,GenericGenerators

import javax.persistence.*;
import java.util.*;


/*Use the object address twice...A straight forward but large method*/
/*We can also assign a name property in Entity...If we do that hibernate will make table with that name*/
@Entity
@Table(name="Aliens")
public class UserDetails {
    @Id @GeneratedValue(strategy=GenerationType.AUTO)/*Four types of strategy are there*/
    private int userId;
    private String userName;

    /*
    * @ElementCollection tells the hibernate to map this collection
    * */
    @ElementCollection
    private Set<Address> address = new HashSet<Address>();

    /*
    * Gave a name of default table which was created by hibernate. And gave the foregin key a new name not the default
    * Also a primary key is generated by hibernate specification
    * /GenericGenerator is one type of generator which hibernate provides....Know about other generators
    * Support for 'hilo' generator has been removed..So hilo-gen can not be used
     * */
    @ElementCollection
    @JoinTable(name = "Playlist",joinColumns=@JoinColumn(name = "userId"))
    @GenericGenerator(name = "increment", strategy = "increment")//Selects the max serial...Increment that one
    @CollectionId(columns = @Column(name = "serial"), type = @Type(type="int"), generator = "increment")
    private List<Songs> songs = new ArrayList<Songs>();

    /*
    * AttributeOverrides -> was needed because we had multiple field in the object.
    * AttributeOverride -> overrides the default field...In this case "rasta" and city..
    * */

    /* If we wnt we can use @Id @GeneratedValue(strategy=GenerationType.AUTO) here above get Method... All the annotations are*/
    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Set<Address> getAddress() {
        return address;
    }

    public void setAddress(Set<Address> address) {
        this.address = address;
    }

    public List<Songs> getSongs() {
        return songs;
    }

    public void setSongs(List<Songs> songs) {
        this.songs = songs;
    }
}
